### ISSUE TITLE
Prophyle Analyze Produces Empty Files

### ISSUE THREAD

**Issue by feltzmc** [karel-brinda/prophyle#248]
Hi Prophyle Team,

I have gotten your tool installed and I have enjoyed the ease of use and speed so far.  Unfortunately I am having an issue visualizing the output from Prophyle classify.  My readset produces an 8GB SAM file when run through classify, and spot checks of the SAM look good.  However, when I run analyze on the SAM file it produces empty output files.

Here are the commands I have run:
```
prophyle download bacteria viruses plasmids
prophyle index -k 31 ~/prophyle/bacteria.nw ~/prophyle/viruses.nw ~/prophyle/plasmids.nw idx_bac_vir_plas
prophyle classify -LAP idx_bac_vir_plas/ ../workdir/NBC01_trimmed.fq > result.sam
prophyle analyze -f sam idx_bac_vir_plas/ NBC01_Prophyle_BVP NBC01_Prophyle_BVP.sam
```

Perhaps one of the options I used is incompatible with analyze?  Any insight would be appreciated.

Thanks,
Matt

**Comment by karel-brinda** [comment]
Hi Matt, thank you for reporting this issue. Would it be possible to upload a beginning of your SAM file (e.g., the headers and first ~10000 assignment records) and the tree (tree.nw)? Attaching files should be possible when you edit this issue (the original message).

@simonepignotti Simone, could you look at the problem, please?

**Comment by feltzmc** [comment]
Certainly, thank you for the quick response!  Here are the requested files:
[Truncated_Prophyle_SAM.sam.txt](https://github.com/karel-brinda/prophyle/files/1285037/Truncated_Prophyle_SAM.sam.txt)
[tree.nw.txt](https://github.com/karel-brinda/prophyle/files/1285039/tree.nw.txt)

**Comment by simonepignotti** [comment]
Hi Matt, sorry to hear that. I am looking at it right now, it should not take long.

**Comment by karel-brinda** [comment]
Thank you for uploading the files. It might be a combination of multiple issues:

* `prophyle analyze` shouldn't return an empty file in any case.
* Some of the SAM records don't look correctly: `c1` tag should never have a value < `h1`, but I can see `c1:i:-1` many times. However, this is rather a minor bug.

@feltzmc I see that you use LCAs for ties (the `-L` parameter). Once we fix this bug, it would be good to look if this is necessary in your case. In my experience, LCAs can confound the results (e.g., due to recombination).

**Comment by feltzmc** [comment]
Interesting and good to know.  I decided to use LCA as I will be running another sample with mixed bacillus species and I wanted to see how it would perform there.  I am doing another classify run now with just the default parameters.  Once that finishes I will let you know if it works with analyze.

Thanks,
Matt

**Comment by simonepignotti** [comment]
I have detected the problem: when the tree has NCBI annotations I use taxid to match nodes in the tree; since we add a numerical index in front of node names when multiple trees are merged, name and taxid do not match anymore.
Running analyze with an index built upon a single tree should work fine, you could try that while we solve this issue. Unfortunately in any case you will need to build a new index.

**Comment by karel-brinda** [comment]
@simonepignotti We should fix this in our code. For instance, if the name of the root is merge_root, then `prophyle analyze` should remove the prefixes from taxids.

Once we implement a better merging strategy, this problem should disappear naturally.

Btw. This bug shows another empty space in our unit tests.

**Comment by feltzmc** [comment]
Ok no problem, I appreciate you guys finding the bug, I will just do my tests on bacteria alone while I wait :)

**Comment by simonepignotti** [comment]
Hi Matt, could you try to run this version of prophyle analyze on your data?
https://github.com/karel-brinda/prophyle/blob/fix_analyze_merge/prophyle/prophyle_analyze.py
The output is not perfect yet, since we don't check for shared subtrees when we merge the trees, but we only add a common root. This will also be improved soon :)

**Comment by feltzmc** [comment]
Thank you for the quick update!  It seems to be working as I am getting output files with both bacterial and viral results!  The only issue I have at the moment is that it seems to have broken the centrifuge abundance metric in the centrifuge output (abundance is 0 for everything)

**Comment by simonepignotti** [comment]
Glad to hear that.
Concerning centrifuge's output, we do not currently use the last field (see http://prophyle.readthedocs.io/en/latest/reference/index.html#analysis-output).

**Comment by simonepignotti** [comment]
PS: my advice is to try different "[statistics](http://prophyle.readthedocs.io/en/latest/reference/index.html#prophyle-analyze)" (for instance `-s wl`, which propagates all the internal nodes assignments to the leaves in their subtree, and then applies a uniform weighting). The analyze command is experimental and we still have to figure out which method works better, and on which data :)

**Comment by feltzmc** [comment]
Ah my mistake, I am making krona plots with the results and thought I was using the abundance column when I was actually using the uniqueReads column (which gives excellent results btw).  I will certainly experiment with the settings and see what I can produce.  Thanks again!

**Comment by simonepignotti** [comment]
You are welcome, let us know how it goes!

Simone

**Comment by karel-brinda** [comment]
Fixed by https://github.com/karel-brinda/prophyle/commit/b9eaa933d6a25f44ad19da165795ddd3e05aaf8b
